allowBuilds:
  sharp: true
  better-sqlite3: true
  '@prisma/engines': true
  prisma: true
  esbuild: true
  '@parcel/watcher': true
  unrs-resolver: true
  vue-demi: true
  '@tailwindcss/oxide': false

overrides:
  h3: 1.15.11
